/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-02-28 02:05:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1550807214933L));
    _jspx_dependants.put("/views/common/adminHeader.jsp", Long.valueOf(1550807210430L));
    _jspx_dependants.put("/views/common/footer.html", Long.valueOf(1550806130233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t*:not(h1) { margin: 0; padding: 0; font-size: 10pt; }\r\n");
      out.write("\t\t\ttable td.title { text-align: left; }\r\n");
      out.write("\t\t\ttable th { background: pink;}\r\n");
      out.write("\t\t\ttable { border: 1px solid black; border-collapse: collapse; width: 300px;}\r\n");
      out.write("\t\t\ttable th, td { border: 1px solid black; text-align: center; padding: 10px 5px 10px 5px; }\r\n");
      out.write("\t\t\ta { text-decoration: none; color: navy; }\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<title>first</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//ajax 코드 구현\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t//주기적으로 반복 요청하려면\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\tsetInterval(function(){ $.ajax(); }, 시간);\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: \"/first/btop3\",\r\n");
      out.write("\t\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"success : \" + data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//객체를 문자열로 변환 처리함\r\n");
      out.write("\t\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//문자열을 배열 객체로 바꿈\r\n");
      out.write("\t\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar values = \"\"\r\n");
      out.write("\t\t\t\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\t\t\t\tvalues += \"<tr><td>\" + json.list[i].bnum + \"</td><td class='title'><a href='/first/bdetail?bno=\" + json.list[i].bno + \"'>\" + decodeURIComponent(json.list[i].btitle).replace(/\\+/gi, \" \") + \"</a></td><td>\" + json.list[i].rcount + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#toplist\").html($(\"#toplist\").html() + values);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//booder top3 옆에 최근 등록한 공지글 3개 출력되게 함\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: \"/first/ntop3\",\r\n");
      out.write("\t\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"success : \" + data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//객체를 문자열로 변환 처리함\r\n");
      out.write("\t\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//문자열을 배열 객체로 바꿈\r\n");
      out.write("\t\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar values = \"\"\r\n");
      out.write("\t\t\t\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\t\t\t\tvalues += \"<tr><td>\" + json.list[i].no + \"</td><td class='title'><a href='/first/ndetail?no=\" + json.list[i].no + \"'>\" + decodeURIComponent(json.list[i].ntitle).replace(/\\+/gi, \" \") + \"</a></td><td>\" + json.list[i].ndate + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#newNotice\").html($(\"#newNotice\").html() + values);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
 if(loginMember != null && loginMember.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>first</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tul {\r\n");
      out.write("\t\t\t\tlist-style: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li {\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tmargin-right: 5px;\r\n");
      out.write("\t\t\t\tbackground: black;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a {\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tpadding-top: 5px;\r\n");
      out.write("\t\t\t\tpadding-bottom: 0;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 100px;\r\n");
      out.write("\t\t\t\theight: 35px;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a:hover {\r\n");
      out.write("\t\t\t\tbackground: pink;\r\n");
      out.write("\t\t\t\ttext-shadow: 1px 1px 2px white;\r\n");
      out.write("\t\t\t\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>first</h1>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/first/index.jsp\">home</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/first/mall\">회원관리</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">공지사항관리</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">게시글관리</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">자료실관리</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>first</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tul {\r\n");
      out.write("\t\t\t\tlist-style: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li {\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tmargin-right: 5px;\r\n");
      out.write("\t\t\t\tbackground: skyblue;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a {\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tpadding-top: 5px;\r\n");
      out.write("\t\t\t\tpadding-bottom: 0;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 100px;\r\n");
      out.write("\t\t\t\theight: 35px;\r\n");
      out.write("\t\t\t\tcolor: navy;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a:hover {\r\n");
      out.write("\t\t\t\tbackground: navy;\r\n");
      out.write("\t\t\t\ttext-shadow: 1px 1px 2px white;\r\n");
      out.write("\t\t\t\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>first</h1>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/first/index.jsp\">home</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/first/nlist\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/first/blist?page=1\">게시글</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">앨범</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">자료실</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t<hr style=\"clear:left;\">\r\n");
      out.write("\t\t<session>\r\n");
      out.write("\t\t\t<h1>firstWebProject</h1>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
 if(loginMember == null){ 
      out.write("\r\n");
      out.write("\t\t\t<!-- <form action=\"login\" method=\"post\"> --> <!-- 상대경로임. -->\r\n");
      out.write("\t\t\t<form action=\"/first/login\" method=\"post\"><!-- 절대경로임. -->\r\n");
      out.write("\t\t\t\t<table width=\"250px\" cellpadding=\"0\" cellspacing=\"5\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"userid\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>암 &nbsp; 호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"userpwd\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/first/views/member/enrollPage.html\">회원가입</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">아이디조회</a> &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">비밀번호조회</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<table width=\"250px\" cellpadding=\"0\" cellspacing=\"5\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( loginMember.getUserName() );
      out.write("님</td>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><a href=\"/first/myinfo?userid=");
      out.print( loginMember.getUserId() );
      out.write("\">내 정보 보기</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"/first/logout\">로그아웃</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"#\">쪽지</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</session>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<div style=\"float: left; border: 1px solid gray; padding: 5px; margin: 5px;\">\r\n");
      out.write("\t\t\t\t<h4>인기 게시글</h4><br>\r\n");
      out.write("\t\t\t\t<table id=\"toplist\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"float: left; border: 1px solid gray; padding: 5px; margin: 5px;\">\r\n");
      out.write("\t\t\t\t<h4>신규 공지글</h4><br>\r\n");
      out.write("\t\t\t\t<table id=\"newNotice\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<hr style=\"clear: left;\">\r\n");
      out.write("\t\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>first</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tfooter {\r\n");
      out.write("\t\t\t\tbackground: navy;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\theight: 70px;\r\n");
      out.write("\t\t\t\tpadding-top: 15px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<h5 align=\"center\">\r\n");
      out.write("\t\t\t\t&copy;2019.02.22 kh.org<br>\r\n");
      out.write("\t\t\t\ttel : 02-1234-5678 &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\tfax : 02-1234-7890\r\n");
      out.write("\t\t\t</h5>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
